# Generated by Django 3.1.4 on 2020-12-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
    ]
